services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otelcol/config.yaml" ]
    volumes:
      - ./otel-collector.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "8080:8080"   # metrics
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"
    depends_on: [ jaeger ]
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  jaeger:
    image: jaegertracing/opentelemetry-all-in-one
    ports:
      - "16686:16686"   # Jaeger UI

