version: "3.8"
services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otelcol/config.yaml" ]
    volumes:
      - ./otel-collector.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"     # OTLP HTTP
      - "9464:9464"     # Prometheus metrics scrape
    depends_on: [ jaeger ]
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"   # Jaeger UI
      - "14250:14250"   # gRPC
